version: '3'

volumes:
  db: {}

services:
  db:
    image: mysql
    restart: always
    expose:
      - 3306
    env_file:
      - .envs/.local/.mysql
    volumes:
      - db:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  flask:
    build:
      context: ./
      dockerfile: ./compose/Dockerfile
    command: /start
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    env_file:
      - .envs/.local/.mysql
    depends_on:
      db:
        condition: service_healthy